## Config file
lr:              1e-4   # Initial learning rate
weight_decay:    1e-5
power:           0.9
epochs:          500    # Number of epochs to train the model
number_classes:  4      # Number of classes in the target dataset
batch_size_tr:   1      # Batch size for train
batch_size_va:   1      # Batch size for validation
modalities:      ['t2f', 't1n', 't1c', 't2w']  # brats: ['t2f', 't1n', 't1c', 't2w']
path_to_data:    './BRATS2024'                # path to dataset (with train/test subfolders)
path_to_log:     './logs/nets'                 # path to save logs / evaluation checkpoints
path_to_ckpts:   './ckpts/nets'

path_to_resume:  null                        # checkpoint path to resume training (null or 'None' for scratch)


progress_p:      0.1                           # value between 0-1 shows how often to report training progress
# validation_p:    0.1                           # validation percentage (not used in current split)
test_p:          0.2                           # Test percentage (20%)
inputshape:      [160,192, 128]
